<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Relevaille extends Model
{
    use HasFactory;

    protected $table = 'relevailles';
    protected $fillable = [
        'nom',
        "annee_fiscale_id",
        "annee_fiscale",
        "date_demande",
        "pae" ,
        "pae_clsc_id",
        "pae_clsc" ,
        "sippe" ,
        "sippe_oui_clsc_id" ,
        "sippe_oui_clsc" ,
        "sippe_non_clsc_id" ,
        "sippe_non_clsc" ,
        "porte_bebe_donne" ,
        "massage_bebe_donne" ,
        "refere" ,
        "refere_organisme" ,
        "langue_parlee" ,
        "statut_citoyen_id" ,
        "statut_citoyen" ,
        "pays_origine",
        "age" ,
        "occupation",
        "monoparentale" ,
        "coopere" ,
        "conjoint_absent_pays" ,
        "conjoint_absent_accouchement" ,
        "conjoint_prenom" ,
        "conjoint_nom",
        "conjoint_occupation" ,
        "courriel_conjoint" ,
        "medecin" ,
        "type_soignant",
        "hopital",
        "dpa" ,
        "nbr_grossesse" ,
        "nbr_enfants" ,
        "age_respectif" ,
        "conditions_particulieres" ,
        "personnes_prevues_accouchement" ,
        "commentaire_presence" ,
        "attentes" ,
        "notes_attentes" ,
        "preoccupations_grossesse" ,
        "sujets_preoccupations_grossesse" ,
        "notes_preoccupations_grossesse",
        "preoccupations_accouchement",
        "sujets_preoccupations_accouchement",
        "notes_preoccupations_accouchement" ,
        "preoccupations_bebe" ,
        "sujets_preoccupations_bebe" ,
        "notes_preoccupations_bebe" ,
        "cours_prenatal" ,
        "notes_prenatal" ,
        "service_connu_id" ,
        "service_connu",
        "accompagnante_id_1",
        "accompagnante_1" ,
        "statut_accompagnante_id_1" ,
        "statut_accompagnante_1" ,
        "accompagnante_id_2" ,
        "accompagnante_2" ,
        "statut_accompagnante_id_2" ,
        "statut_accompagnante_2" ,
        "date_remise_bilan" ,
        "montant_paye" ,
        "numero_cheque",
        "date_cheque",
        "dossier_bilan" ,
        "date_remise_bilan_acc2" ,
        "montant_paye_acc2" ,
        "numero_cheque_acc2" ,
        "date_cheque_acc2",
        "dossier_bilan_acc2" ,
        "evaluation_document" ,
        "sollicite_don",
        "date_sollicitation_don" ,
        "don_date" ,
        "don_montant" ,
        "don_numero_recu" ,
        "don_type_paiement" ,
        "document_sollicite_evaluation" ,
        "notes_generales",
        "dossier_demande_stage" ,
        "dossier_marrainage" ,
        "dyade" ,
        "stagiaire" ,
        "stage_paye",
        "date_paiement_stage" ,
        "montant_paye_par_stagiaire",
        "bilan_supervision_stage_remis" ,
        "bilan_supervision_stage_document",
        "montant_paye_marrainee" ,
        "numero_cheque_marrainee",
        "date_cheque_marrainee" ,
        "notes_accompagnement",
        "anxiete",
        "notes_anxiete",
        "accepter_contact_an" ,
        "accepter_contact_organisme" ,
        "accepter_statistiques" ,
        "statut_dossier",
        "uid" ,
        "avertissement_50jours_acc1",
        "avertissement_60jours_acc1" ,
        "avertissement_50jours_acc2" ,
        "avertissement_60jours_acc2",
        "avertissement_sippe_pae_rosemont",

    ];

}
